trigger:
  batch: true

jobs:
- job: 'Formatting'
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET'
    inputs:
      version: 7.0.x
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      restoreArguments: '--force --locked-mode'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.Config'
  - task: DotNetCoreCLI@2
    displayName: 'Formatting'
    inputs:
      command: 'format'
      arguments: '--no-restore --verify-no-changes'