name: Formatting

on:
  push:
    branches:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore
        run: |
          dotnet restore --force --locked-mode
      - name: Formatting
        run: |
          dotnet format --no-restore --verify-no-changes
